name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      HAS_DOCKER_CREDS: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
      HAS_HF_TOKEN: ${{ secrets.HF_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t mlops-reputation-monitor:latest .

      - name: Log in to Docker Hub
        if: env.HAS_DOCKER_CREDS == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: env.HAS_DOCKER_CREDS == 'true'
        run: |
          docker tag mlops-reputation-monitor:latest ${{ secrets.DOCKER_USERNAME }}/mlops-reputation-monitor:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-reputation-monitor:latest

      - name: Upload model to HuggingFace (optional)
        if: env.HAS_HF_TOKEN == 'true'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          python - <<'PY'
          from huggingface_hub import HfApi
          print("HF token presente, puoi caricare il modello in uno step separato")
          PY
